namespace Appalachia.Utility.Constants
{
    public static class SHK
    {
        public const string _ = " _";
        public const string _CTRL = " %";
        public const string _SHFT = " #";
        public const string _ALT = " &";
        public const string _CTRL_SHFT = " %#";
        public const string _ALT_SHFT = " &#";
        public const string _CTRL_ALT = " %&";
        public const string _CTRL_ALT_SHFT = " %&#";

        public const string A = "A";
        public const string B = "B";
        public const string C = "C";
        public const string D = "D";
        public const string E = "E";
        public const string F = "F";
        public const string G = "G";
        public const string H = "H";
        public const string I = "I";
        public const string J = "J";
        public const string K = "K";
        public const string L = "L";
        public const string M = "M";
        public const string N = "N";
        public const string O = "O";
        public const string P = "P";
        public const string Q = "Q";
        public const string R = "R";
        public const string S = "S";
        public const string T = "T";
        public const string U = "U";
        public const string V = "V";
        public const string W = "W";
        public const string X = "X";
        public const string Y = "Y";
        public const string Z = "Z";

        public const string a = "a";
        public const string b = "b";
        public const string c = "c";
        public const string d = "d";
        public const string e = "e";
        public const string f = "f";
        public const string g = "g";
        public const string h = "h";
        public const string i = "i";
        public const string j = "j";
        public const string k = "k";
        public const string l = "l";
        public const string m = "m";
        public const string n = "n";
        public const string o = "o";
        public const string p = "p";
        public const string q = "q";
        public const string r = "r";
        public const string s = "s";
        public const string t = "t";
        public const string u = "u";
        public const string v = "v";
        public const string w = "w";
        public const string x = "x";
        public const string y = "y";
        public const string z = "z";

        public const string _0 = "0";
        public const string _1 = "1";
        public const string _2 = "2";
        public const string _3 = "3";
        public const string _4 = "4";
        public const string _5 = "5";
        public const string _6 = "6";
        public const string _7 = "7";
        public const string _8 = "8";
        public const string _9 = "9";

        public const string Left = "LEFT";
        public const string Up = "UP";
        public const string Right = "RIGHT";
        public const string Down = "DOWN";
        public const string PageDown = "PGDN";
        public const string PageUp = "PGUP";
        public const string Home = "HOME";
        public const string Insert = "INS";
        public const string Delete = "DEL";
        public const string End = "END";
        public const string Tab = "TAB";
        public const string Space = "SPACE";
        public const string F1 = "F1";
        public const string F2 = "F2";
        public const string F3 = "F3";
        public const string F4 = "F4";
        public const string F5 = "F5";
        public const string F6 = "F6";
        public const string F7 = "F7";
        public const string F8 = "F8";
        public const string F9 = "F9";
        public const string F10 = "F10";
        public const string F11 = "F11";
        public const string F12 = "F12";
        public const string Quote = "'";
        public const string Comma = ",";
        public const string Minus = "-";
        public const string Period = ".";
        public const string Slash = "/";
        public const string Semicolon = ";";
        public const string Equal = "=";
        public const string LeftBracket = "[";
        public const string RightBracket = "]";
        public const string Backslash = "\\";
        public const string BackQuote = "`";
    }
}
